name: Generate the list of users
on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  get-starred-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - run: rm -rdf starred_users && mkdir starred_users
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN_PAT }}
          script: |
            const fs = require('fs');
            fs.writeFileSync(process.cwd() + '/starred_users/gautamkrishnar', 'done', { encoding: 'utf-8', });
            github
              .paginate(github.rest.activity.listStargazersForRepo, {
                owner: "gautamkrishnar",
                repo: "blog-post-workflow",
                per_page: 100
              })
              .then((stars) => {
                stars.forEach((item) => {
                  const filename = process.cwd() + '/starred_users/' + item.login;
                  console.log(filename);
                  fs.writeFileSync(filename, 'done', { encoding: 'utf-8', });
                });
              });
      - run: |
          git config --global user.name "gkr-bot"
          git config --global user.email "gkr@tuta.io"
          git add starred_users || true
          git commit -m "Added usernames" || true
          git push || true
      - uses: gautamkrishnar/keepalive-workflow@master
