name: Generate the list of users
on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            github
              .paginate(github.rest.activity.listStargazersForRepo, {
                owner: "gautamkrishnar",
                repo: "blog-post-workflow",
              })
              .then((stars) => {
                stars.forEach((item) => {
                  console.log(process.cwd() + '/starred_users/' + item.login);
                  fs.writeFileSync(process.cwd() + '/starred_users/' + item.login, 'done', { encoding: 'utf-8', });
                });
              });
      - run: ls /home/runner/work/is-starred-blog-post-workflow/is-starred-blog-post-workflow/starred_users
