name: Generate the list of users
on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const count = 0;
            github
              .paginate(github.rest.activity.listStargazersForRepo, {
                owner: "gautamkrishnar",
                repo: "blog-post-workflow",
              })
              .then((stars) => {
                count = count + 1;
                console.log(count)
              });
              
