name: Generate the list of users
on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            console.log();
            //requiring path and fs modules
            const path = require('path');
            //joining path of directory 
            const directoryPath = path.join(process.cwd());
            //passsing directoryPath and callback function
            fs.readdir(directoryPath, function (err, files) {
                //handling error
                if (err) {
                    return console.log('Unable to scan directory: ' + err);
                } 
                //listing all files using forEach
                files.forEach(function (file) {
                    // Do whatever you want to do with the file
                    console.log(file); 
                });
            });
      - run: ls /home/runner/work/is-starred-blog-post-workflow/is-starred-blog-post-workflow
