name: Generate the list of users
on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            github
              .paginate(github.rest.activity.listStargazersForRepo, {
                owner: "gautamkrishnar",
                repo: "blog-post-workflow",
              })
              .then((stars) => {
                stars.forEach((item) => {
                  fs.writeFileSync('starred_users/' + item.login, '');
                });
              });
      - run: ls starred_users
